@startuml
class GestorBaseController 
class FiltroBaseController
class TablaBaseController
interface IfiltroGenerico
FiltroBaseController*-->IfiltroGenerico
GestorBaseController*-->FiltroBaseController
GestorBaseController*-->TablaBaseController
GestorBaseController-->ModalService
GestorBaseController-->LoadingService
GestorBaseController-->AlertService
GestorBaseController-->IHttpService
GestorBaseController-->IRespuestaGenerica
GestorBaseController-->ISolicitudGenerica
GestorBaseController*-->ComponenteFiltro
GestorBaseController*-->ComponenteRegistro
TablaBaseController*-->PaginacionController
class HttpServiceConcreto implements IHttpService
class FiltroConcreto implements IfiltroGenerico 
class PaginacionController 
class ModalService
class LoadingService 
class AlertService 
interface IHttpService 
interface IRespuestaGenerica
interface ISolicitudGenerica
class RespuestaConcreta implements IRespuestaGenerica
class SolicitudConcreta implements ISolicitudGenerica
class ModalBase
class ComponenteFiltro extends ModalBase
class ComponenteRegistro extends ModalBase
@enduml
